config/routes.rb
Qualidade::Application.routes.draw do
  
  resources :items

  resources :controls do
    member do 
      get 'variaveis_tipo_1_media'
      get 'variaveis_tipo_1_amplitude'
      get 'variaveis_tipo_2_media'
      get 'variaveis_tipo_2_desvio_padrao'
      get 'variaveis_tipo_3_mediana'
      get 'variaveis_tipo_3_amplitude'
      get 'atributos_p'
      get 'atributos_np'
      get 'atributos_c'
    end
    resources :sheets do
      match :processar, :on => :member
    end
    resources :samples
  end

  devise_for :users
  resources :users

  get "home/index"

  root :to => "home#index"
end

app/models/sample.rb
class Sample < ActiveRecord::Base

  has_paper_trail

  belongs_to :control

  has_many :items, :dependent=>:destroy
  has_many :limit_calculations, :dependent=>:destroy
  has_many :additional_informations


  def calcular_media
    self.media = self.items.average(:valor)
    self.amplitude = self.items.maximum(:valor)-self.items.minimum(:valor)
    self.desvio_padrao = self.items.select("stddev(valor) as desvio")[0].desvio.to_f
    self.mediana = self.calcular_mediana
    self.save

    # calcular os limites para Tipo 1 do Controle por Variáveis
  end
  
  def limite_superior tipo
    @constant = Constant.find_last_by_tamanho(self.items.size)
    resultado = case tipo
       when "media" then (self.control.media_das_medias+@constant.a2*self.control.media_das_amplitudes).round(2)
       when "amplitude" then (@constant.d4*self.control.media_das_amplitudes).round(2)
       when "desvio_padrao" then (@constant.b4*self.control.media_dos_desvios).round(2)
       when "mediana" then (self.control.media_das_medianas+@constant.a2*self.control.media_das_amplitudes).round(2)
    end
    ((self.control.ls_padrao!=nil and @control.ls_padrao>0) ? self.control.ls_padrao : resultado)
  end
  
  def limite_central tipo
    @constant = Constant.find_last_by_tamanho(self.items.size)
    case tipo
       when "media" then self.control.media_das_medias.round(2)
       when "amplitude" then self.control.media_das_amplitudes.round(2)
       when "desvio_padrao" then self.control.media_dos_desvios.round(2)
       when "mediana" then self.control.media_das_medianas.round(2)
    end
  end
  
  def limite_inferior tipo
    @constant = Constant.find_last_by_tamanho(self.items.size)
    resultado = case tipo
       when "media" then (self.control.media_das_medias-@constant.a2*self.control.media_das_amplitudes).round(2)
       when "amplitude" then (@constant.d3*self.control.media_das_amplitudes).round(2)
       when "desvio_padrao" then (@constant.b3*self.control.media_dos_desvios).round(2)
       when "mediana" then (self.control.media_das_medianas-@constant.a2*self.control.media_das_amplitudes).round(2)
    end
    (self.control.li_padrao!=nil ? self.control.li_padrao : resultado)
  end

  def calcular_mediana
    items = self.items.order("valor ASC")
    n = (items.length - 1) / 2 # Middle of the array
    n2 = (items.length) / 2 # Other middle of the array.
    # Used only if amount in array is even
    if items.length % 2 == 0 # If number is even
      median = (items[n].valor + items[n2].valor) / 2
    else
      median = items[n].valor
    end
    return median
  end
  
  
  def calcular_carta_p
    @lc = self.limit_calculations.where({:categoria=>:atributos, :tipo=>:p, :calculo=>:lc}).limit(1).last
    if @lc==nil
      @lc = self.limit_calculations.build({:categoria=>:atributos, :tipo=>:p, :calculo=>:lc})
    end
    @lc.valor = self.control.fracao_de_nao_conformes
    @lc.save
    
    @calculo = Math.sqrt((self.control.fracao_de_nao_conformes*(1-self.control.fracao_de_nao_conformes))/self.tamanho_da_amostra)
    
    @lcs = self.limit_calculations.where({:categoria=>:atributos, :tipo=>:p, :calculo=>:lcs}).limit(1).last
    if @lcs==nil
      @lcs = self.limit_calculations.build({:categoria=>:atributos, :tipo=>:p, :calculo=>:lcs})
    end
    @lcs.valor = @lc.valor+3*@calculo
    @lcs.save
    
    @lci = self.limit_calculations.where({:categoria=>:atributos, :tipo=>:p, :calculo=>:lci}).limit(1).last
    if @lci==nil
      @lci = self.limit_calculations.build({:categoria=>:atributos, :tipo=>:p, :calculo=>:lci})
    end
    @lci.valor = (@lc.valor-3*@calculo)<=0 ? 0 : (@lc.valor-3*@calculo)
    @lci.save
    
  end
  
  def calcular_carta_np
    @lc = self.limit_calculations.where({:categoria=>:atributos, :tipo=>:np, :calculo=>:lc}).limit(1).last
    if @lc==nil
      @lc = self.limit_calculations.build({:categoria=>:atributos, :tipo=>:np, :calculo=>:lc})
    end
    @lc.valor = self.control.media_de_itens_defeituosos
    @lc.save
    
    @calculo = self.control.desvio_padrao_de_nao_conformidades
    
    @lcs = self.limit_calculations.where({:categoria=>:atributos, :tipo=>:np, :calculo=>:lcs}).limit(1).last
    if @lcs==nil
      @lcs = self.limit_calculations.build({:categoria=>:atributos, :tipo=>:np, :calculo=>:lcs})
    end
    @lcs.valor = @lc.valor+3*@calculo
    @lcs.save
    
    @lci = self.limit_calculations.where({:categoria=>:atributos, :tipo=>:np, :calculo=>:lci}).limit(1).last
    if @lci==nil
      @lci = self.limit_calculations.build({:categoria=>:atributos, :tipo=>:np, :calculo=>:lci})
    end
    @lci.valor = (@lc.valor-3*@calculo)<=0 ? 0 : (@lc.valor-3*@calculo)
    @lci.save
    
  end
  
  def calcular_carta_c
    
    @calculo = self.control.raiz_quadrada_da_media_das_conformidades
    
    @lc = self.limit_calculations.where({:categoria=>:atributos, :tipo=>:c, :calculo=>:lc}).limit(1).last
    if @lc==nil
      @lc = self.limit_calculations.build({:categoria=>:atributos, :tipo=>:c, :calculo=>:lc})
    end
    @lc.valor = self.control.media_de_itens_defeituosos
    @lc.save
    
    
    
    @lcs = self.limit_calculations.where({:categoria=>:atributos, :tipo=>:c, :calculo=>:lcs}).limit(1).last
    if @lcs==nil
      @lcs = self.limit_calculations.build({:categoria=>:atributos, :tipo=>:c, :calculo=>:lcs})
    end
    @lcs.valor = @lc.valor+3*@calculo
    @lcs.save
    
    @lci = self.limit_calculations.where({:categoria=>:atributos, :tipo=>:c, :calculo=>:lci}).limit(1).last
    if @lci==nil
      @lci = self.limit_calculations.build({:categoria=>:atributos, :tipo=>:c, :calculo=>:lci})
    end
    @lci.valor = (@lc.valor-3*@calculo)<=0 ? 0 : (@lc.valor-3*@calculo)
    @lci.save
    
  end

end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_filter :find_control
  
  def find_control
    @control = Control.find(params[:control_id])
  end
  
  def index
    @samples = @control.samples.order("tempo ASC").all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @samples }
    end
  end

  def show
    @sample = Sample.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sample }
    end
  end

  def new
    @sample = @control.samples.build  

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sample }
    end
  end

  def edit
    @sample = Sample.find(params[:id])
  end

  def create
    @sample = Sample.new(params[:sample])

    respond_to do |format|
      if @sample.save
        format.html { redirect_to(@sample, :notice => 'Sample was successfully created.') }
        format.xml  { render :xml => @sample, :status => :created, :location => @sample }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sample.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @sample = Sample.find(params[:id])

    respond_to do |format|
      if @sample.update_attributes(params[:sample])
        format.html { redirect_to(@sample, :notice => 'Sample was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sample.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to(samples_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/samples_helper.rb
module SamplesHelper
  
end

app/views/samples/_form.html.erb
<div class="field">
	<%= f.label :tempo, "Hora" %><br />
	<%= f.datetime_select :tempo %>
</div>

app/views/samples/_sidebar.html.erb
<div id="right-sidebar"> 
	<div class="innerdiv"> 
		<h2 class="head">Ferramentas</h2> 
		<div class="innercontent clear"> 
			<h4>Análises</h4> 
			<ul id="comments"> 
				<% if @control.items.size>0 %>
				<li>
					<%= image_tag "icons/stats.png"%>
					<span class="sender"><%= link_to "Média e Amplitude", variaveis_tipo_1_media_control_path(@control)%></span> 
					<span class="description"><%= link_to "Controle Por Variáveis", variaveis_tipo_1_media_control_path(@control)%></span> 
					<span class="date"></span> </a> 
					<br class="clear"/> 
				</li> 
				
				<li>
					<%= image_tag "icons/stats.png"%>
					<span class="sender"><%= link_to "Média e Desvio Padrão", variaveis_tipo_2_media_control_path(@control)%></span> 
					<span class="description"><%= link_to "Controle Por Variáveis", variaveis_tipo_2_media_control_path(@control)%></span> 
					<span class="date"></span> </a> 
					<br class="clear"/> 
				</li>
				
				<li>
					<%= image_tag "icons/stats.png"%>
					<span class="sender"><%= link_to "Mediana e Amplitude", variaveis_tipo_3_mediana_control_path(@control)%></span> 
					<span class="description"><%= link_to "Controle Por Variáveis", variaveis_tipo_3_mediana_control_path(@control)%></span> 
					<span class="date"></span> </a> 
					<br class="clear"/> 
				</li>
				<% else %>
				<li>
					<%= image_tag "icons/stats.png"%>
					<span class="sender"><%= link_to "Controle por Atributos", atributos_p_control_path(@control)%></span> 
					<span class="description"><%= link_to "Carta P", atributos_p_control_path(@control)%></span> 
					<span class="date"><%= link_to "Fração de defeituosos", atributos_p_control_path(@control)%></span> </a> 
					<br class="clear"/> 
				</li>
				
				<li>
					<%= image_tag "icons/stats.png"%>
					<span class="sender"><%= link_to "Controle por Atributos", atributos_np_control_path(@control)%></span> 
					<span class="description"><%= link_to "Carta NP", atributos_np_control_path(@control)%></span> 
					<span class="date"><%= link_to "Fração de defeituosos", atributos_np_control_path(@control)%></span> </a> 
					<br class="clear"/> 
				</li>
				
				<li>
					<%= image_tag "icons/stats.png"%>
					<span class="sender"><%= link_to "Controle por Atributos", atributos_c_control_path(@control)%></span> 
					<span class="description"><%= link_to "Carta C", atributos_c_control_path(@control)%></span> 
					<span class="date"><%= link_to "Não-conformidades por unidade", atributos_c_control_path(@control)%></span> </a> 
					<br class="clear"/> 
				</li>
				<% end %>
			</ul> 
		</div> 
	</div> 
</div>

app/views/samples/_tabela.html.erb
<table class="full">
	<thead>
		<tr class="alt">
			<th>Amostra</th>
			<th>Data</th>
			
			<% if @control.items.size>0 %>
			<th>Ítens</th>
						<th>Média</th>
						<th>Amplitude</th>
						<th>Desvio Padrão</th>
						<th>Mediana</th>
						
						<% else %>
						
						<th>Tamanho da amostra</th>
						<th>Defeitos</th>
						
						<% end %>
						<th></th>
		</tr>
	</thead>
	
	<tbody>
		<% @samples.each do |amostra| %>
		<tr class="<%= cycle('alt','')%>">
			<td><%= amostra.lote %></td>
			<td><%= l amostra.tempo, :format=>:short %></td>
			
			<% if @control.items.size>0 %>
			<td><%= amostra.items.size %></td>
						<td><%= amostra.media.round(2) %></td>
						<td><%= amostra.amplitude.round(2) %></td>
						<td><%= amostra.desvio_padrao.round(2) %></td>
						<td><%= amostra.mediana.round(2) %></td>
						
						<% else %>
						
						<td><%= amostra.tamanho_da_amostra.round(2) %></td>
						<td><%= amostra.itens_defeituosos.round(2) %></td>
						
						<% end %>
			
			<td>
			<!-- Icons -->
			<%= link_to image_tag('icons/edit.png'), edit_control_sample_path(@control, amostra)%>
			</td>
		</tr>
		<% end %>
		</tbody>
</table>

app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<div class="innerdiv"> 
	<h2 class="head-alt-white">Controle</h2> 
	<ul class="tabs">
		<li><%= link_to "Informações", @control%></li>
		<li><%= link_to "Arquivos", control_sheets_path(@control)%></li>
		<li><%= link_to "Amostras", control_samples_path(@control), :class=>"current"%></li>
	</ul>
	<div class="innercontent">
		<div class="panes">
			<%= render "tabela" %>
		</div>
	</div>
</div>

app/views/samples/new.html.erb
<%= form_for([@control, @sample]) do |f| %>
<% if @sample.errors.any? %>
<div class="notification errors">
	<%= pluralize(@sample.errors.count, "erro impediu", "erros impediram") %> o registro de ser salvo:
	<p class="collapsible collapsible-heading"><a href="#" class="collapsible-heading-toggle"><span class="collapsible-heading-status">Ocultar </span>Mostrar detalhes!</a></p>
	<ul class="collapsible-content" aria-hidden="false">
		<% @sample.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>



<div class="innerdiv"> 
	<!-- Tabs --> 
	<h2 class="head-alt-white">Amostras</h2> 
	<div class="innercontent"> 
		<!-- tab "panes" --> 
		<div class="panes"> 
			<div> 
				<fieldset> 
					<legend>Nova Amostra</legend> 
					<%= render "form", {:f=>f} %>
					<input class="button black bigger" type="submit" value="Salvar">
				</fieldset> 
			</div> 
		</div> 
	</div> 
</div> 
<% end %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Control:</b>
  <%= @sample.control %>
</p>

<p>
  <b>Tempo:</b>
  <%= @sample.tempo %>
</p>


<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>