config/routes.rb
Qualidade::Application.routes.draw do
  
  resources :items

  resources :controls do
    member do 
      get 'variaveis_tipo_1_media'
      get 'variaveis_tipo_1_amplitude'
      get 'variaveis_tipo_2_media'
      get 'variaveis_tipo_2_desvio_padrao'
      get 'variaveis_tipo_3_mediana'
      get 'variaveis_tipo_3_amplitude'
      get 'atributos_p'
      get 'atributos_np'
      get 'atributos_c'
    end
    resources :sheets do
      match :processar, :on => :member
    end
    resources :samples
  end

  devise_for :users
  resources :users

  get "home/index"

  root :to => "home#index"
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  
  has_paper_trail
  
  belongs_to :control
  
  has_attached_file :arquivo

  
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_filter :find_control
  
  def find_control
    @control = Control.find(params[:control_id])
  end

  def index
    @sheets = @control.sheets.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sheets }
    end
  end

  def show
    @sheet = Sheet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sheet }
    end
  end

  def new
    @sheet = @control.sheets.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sheet }
    end
  end

  def edit
    @sheet = Sheet.find(params[:id])
  end

  def create
    @sheet = @control.sheets.create(params[:sheet])

    respond_to do |format|
      if @sheet.save
        format.html { redirect_to([@sheet.control, @sheet], :notice => 'Planilha Importada com sucesso.') }
        format.xml  { render :xml => @sheet, :status => :created, :location => @sheet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sheet.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @sheet = Sheet.find(params[:id])

    respond_to do |format|
      if @sheet.update_attributes(params[:sheet])
        format.html { redirect_to(@sheet, :notice => 'Planilha atualizada com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sheet.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @sheet = Sheet.find(params[:id])
    @sheet.destroy

    respond_to do |format|
      format.html { redirect_to(control_sheets_url(@control)) }
      format.xml  { head :ok }
    end
  end

  def processar
    @sheet = Sheet.find(params[:id])
    planilha = @sheet.arquivo.planilha
    
    ((planilha.first_row+1)..planilha.last_row).each do |index|
      @sample=@control.samples.build
      if params[:data]
        @sample.tempo = planilha.cell(index, params[:data][0].to_i)
      end
      if params[:lote]
        @sample.lote = planilha.cell(index, params[:lote][0].to_i)
      end
      @sample.save
      if params[:adicional]
        params[:adicional].each do |adicional|
          @additional_information = AdditionalInformation.new(:informacao=>planilha.cell(1, adicional), :conteudo=>planilha.cell(index, adicional), :sample_id=>@sample.id)
          @additional_information.save
        end
      end
      
      if params[:amostra]
        params[:amostra].each do |adicional|
          if planilha.cell(index, adicional.to_i)!=nil
            @item = Item.new(:valor=>planilha.cell(index, adicional.to_i), :sample_id=>@sample.id)
            @item.save
          end
        end
      end
      @sample.calcular_media
    end
    redirect_to control_samples_path(@control)
  end

end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/sheets/_arquivo.html.erb
<table class="full">
	<thead>
		<tr class="alt">
			<th>Coluna</th>
			<th>ID do Lote</th>
			<th>Data</th>
			<th>Amostra</th>
			<th>Informação Adicional</th>
		</tr>
	</thead>
	
	<tbody>
		<% (1..@sheet.arquivo.colunas).each do |coluna| %>
		<tr class="<%= cycle('alt','')%>">
			<td><%= @sheet.arquivo.planilha.cell(1, coluna) %></td>
			<td><%= check_box_tag("lote[]", coluna, false, :class=>"lote") %></td>
			<td><%= check_box_tag("data[]", coluna, false, :class=>"data") %></td>
			<td><%= check_box_tag("amostra[]", coluna) %></td>
			<td><%= check_box_tag("adicional[]", coluna, false, :class=>"adicional") %></td>
		</tr>
		<% end %>
		</tbody>
</table>

app/views/sheets/_form.html.erb
<%= f.input :arquivo %>

app/views/sheets/_form2.html.erb
<%= f.input :initial_time, :label=>"Hora inicial" %>
<%= f.input :increment_value, :label=>"Incrementar", :as=>:string %>
<%= f.input :incremente_type, :label=>"A cada", :collection=>[["Minutos", "minute"],["Horas", "hour"], ["Dias", "day"]] %>

app/views/sheets/_tabela.html.erb
<table class="full">
	<thead>
		<tr class="alt">
			<th>Arquivo</th>
			<th>Nome</th>
			<th>Data</th>
			<th>Linhas</th>
			<th>Colunas</th>
			<th></th>
		</tr>
	</thead>
	
	<tbody>
		<% @sheets.each_with_index do |planilha, i| %>
		<tr class="<%= cycle('alt','')%>">
			<td><%= i+1 %></td>
			<td><%= link_to planilha.arquivo.original_filename, [@control, planilha] %></td>
			<td><%= l planilha.created_at, :format=>:short %></td>
			<td><%= planilha.arquivo.linhas %></td>
			<td><%= planilha.arquivo.colunas %></td>
			<td>
			<!-- Icons -->
			<%= link_to image_tag('icons/edit.png'), edit_control_sheet_path(planilha.control, planilha)%>
			<%= link_to image_tag('icons/delete.png'), [planilha.control, planilha], :method=>:delete %>
			</td>
		</tr>
		<% end %>
		</tbody>
</table>

app/views/sheets/edit.html.erb
<h1>Editing sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @sheet %> |
<%= link_to 'Back', sheets_path %>

app/views/sheets/index.html.erb
<div class="innerdiv"> 
	<h2 class="head-alt-white">Controle</h2> 
	<%= link_to "Importar Arquivo", new_control_sheet_path(@control), :class=>"button top-button" %>
	<ul class="tabs">
		<li><%= link_to "Informações", @control%></li>
		<li><%= link_to "Arquivos", control_sheets_path(@control), :class=>"current"%></li>
		<li><%= link_to "Amostras", control_samples_path(@control)%></li>
	</ul>
	<div class="innercontent">
		<div class="panes">
				<%= render "tabela" %>
		</div>
	</div>
</div>

app/views/sheets/new.html.erb
<%= simple_form_for([@control, @sheet], :html => { :multipart => true }) do |f| %>
<% if @sheet.errors.any? %>
<div class="notification errors">
	<%= pluralize(@sheet.errors.count, "erro impediu", "erros impediram") %> o registro de ser salvo:
	<p class="collapsible collapsible-heading"><a href="#" class="collapsible-heading-toggle"><span class="collapsible-heading-status">Ocultar </span>Mostrar detalhes!</a></p>
	<ul class="collapsible-content" aria-hidden="false">
		<% @sheet.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>



<div class="innerdiv"> 
	<!-- Tabs --> 
	<h2 class="head-alt-white">Amostras</h2> 
	<div class="innercontent"> 
		<!-- tab "panes" --> 
		<div class="panes"> 
			<div> 
				<fieldset> 
					<legend>Novas Amostras</legend> 
					<%= render "form", {:f=>f} %>
					<input class="button black bigger" type="submit" value="Salvar">
				</fieldset> 
			</div> 
		</div> 
	</div> 
</div> 
<% end %>

app/views/sheets/show.html.erb
<%= form_for ([@control, @sheet], :url=>processar_control_sheet_path(@control, @sheet), :method=>:post) do %>
<% if @sheet.errors.any? %>
<div class="notification errors">
	<%= pluralize(@sheet.errors.count, "erro impediu", "erros impediram") %> o registro de ser salvo:
	<p class="collapsible collapsible-heading"><a href="#" class="collapsible-heading-toggle"><span class="collapsible-heading-status">Ocultar </span>Mostrar detalhes!</a></p>
	<ul class="collapsible-content" aria-hidden="false">
		<% @sheet.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>



<div class="innerdiv"> 
	<!-- Tabs --> 
	<h2 class="head-alt-white">Amostras</h2> 
	<div class="innercontent"> 
		<!-- tab "panes" --> 
		<div class="panes"> 
			<div> 
				<fieldset> 
					<legend>Importar</legend> 
					<%= render "arquivo" %>
					<input class="button black bigger" type="submit" value="Processar">
				</fieldset> 
			</div> 
		</div> 
	</div> 
</div> 
<% end %>