config/routes.rb
Qualidade::Application.routes.draw do
  
  resources :items

  resources :controls do
    member do 
      get 'variaveis_tipo_1_media'
      get 'variaveis_tipo_1_amplitude'
      get 'variaveis_tipo_2_media'
      get 'variaveis_tipo_2_desvio_padrao'
      get 'variaveis_tipo_3_mediana'
      get 'variaveis_tipo_3_amplitude'
      get 'atributos_p'
      get 'atributos_np'
      get 'atributos_c'
    end
    resources :sheets do
      match :processar, :on => :member
    end
    resources :samples
  end

  devise_for :users
  resources :users

  get "home/index"

  root :to => "home#index"
end

app/models/control.rb
class Control < ActiveRecord::Base

  has_paper_trail

  has_many :samples, :dependent=>:destroy
  has_many :sheets, :dependent=>:destroy
  has_many :limit_calculations, :through=>:samples
  has_many :items, :through=>:samples

  belongs_to :user

  validates_presence_of :nome


  def indice limite, categoria, tipo, calculo=nil
    if calculo!=nil
      self.limit_calculations.where({:categoria=>categoria, :tipo=>tipo, :calculo=>"#{limite}_of_#{calculo}"})
    else
      self.limit_calculations.where({:categoria=>categoria, :tipo=>tipo, :calculo=>limite})
    end
  end

  def indice_por_atributo limite, categoria, tipo
    self.limit_calculations.where({:categoria=>categoria, :tipo=>tipo, :calculo=>limite})
  end

  def media_das_medias
    self.samples.average(:media)
  end
  
  def media_das_medianas
    self.samples.average(:mediana)
  end

  def media_das_amplitudes
    self.samples.average(:amplitude)
  end

  def media_dos_desvios
    self.samples.average(:desvio_padrao)
  end

  def media_das_medianas
    self.samples.average(:mediana)
  end

  def fracao_de_nao_conformes
    self.samples.sum(:itens_defeituosos)/self.samples.sum(:tamanho_da_amostra)
  end

  def media_de_itens_defeituosos
    self.samples.average(:itens_defeituosos)
  end

  def desvio_padrao_de_nao_conformidades
    self.samples.select("stddev(itens_defeituosos) as desvio")[0].desvio.to_f
  end

  def raiz_quadrada_da_media_das_conformidades
    Math.sqrt(self.samples.average(:itens_defeituosos))
  end


end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController

  def index

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @controls }
    end
  end

  def show
    @control = Control.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @control }
    end
  end

  def new
    @control = Control.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @control }
    end
  end

  def edit
    @control = Control.find(params[:id])
  end

  def create
    @control = Control.new(params[:control])
    @control.user = current_user
    respond_to do |format|
      if @control.save
        format.html { redirect_to(@control, :notice => 'Controle criado com sucesso.') }
        format.xml  { render :xml => @control, :status => :created, :location => @control }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @control.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @control = Control.find(params[:id])
    @control.user = current_user
    respond_to do |format|
      if @control.update_attributes(params[:control])
        format.html { redirect_to(@control, :notice => 'Controle atualizado com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @control.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @control = Control.find(params[:id])
    @control.destroy

    respond_to do |format|
      format.html { redirect_to(controls_url) }
      format.xml  { head :ok }
    end
  end
  
  def variaveis_tipo_1_media
    @control = Control.find(params[:id])
    render "controls/variaveis/tipo1/media"
  end
  
  def variaveis_tipo_1_amplitude
    @control = Control.find(params[:id])

    @lc_amplitude = @control.indice :lc, :variaveis, :tipo1, :amplitude
    @lci_amplitude = @control.indice :lci, :variaveis, :tipo1, :amplitude
    @lcs_amplitude = @control.indice :lcs, :variaveis, :tipo1, :amplitude
    
    render "controls/variaveis/tipo1/amplitude"
  end
  
  def variaveis_tipo_2_media
    @control = Control.find(params[:id])
    
    @lc_media = @control.indice :lc, :variaveis, :tipo2, :media
    @lci_media = @control.indice :lci, :variaveis, :tipo2, :media
    @lcs_media = @control.indice :lcs, :variaveis, :tipo2, :media
    
    render "controls/variaveis/tipo2/media"
  end
  
  def variaveis_tipo_2_desvio_padrao
    @control = Control.find(params[:id])

    @lc_amplitude = @control.indice :lc, :variaveis, :tipo2, :desvio_padrao
    @lci_amplitude = @control.indice :lci, :variaveis, :tipo2, :desvio_padrao
    @lcs_amplitude = @control.indice :lcs, :variaveis, :tipo2, :desvio_padrao
    
    render "controls/variaveis/tipo2/desvio_padrao"
  end
  
  def variaveis_tipo_3_mediana
    @control = Control.find(params[:id])
    
    @lc_mediana = @control.indice :lc, :variaveis, :tipo3, :mediana
    @lci_mediana = @control.indice :lci, :variaveis, :tipo3, :mediana
    @lcs_mediana = @control.indice :lcs, :variaveis, :tipo3, :mediana
    
    render "controls/variaveis/tipo3/mediana"
  end
  
  def variaveis_tipo_3_amplitude
    @control = Control.find(params[:id])

    @lc_amplitude = @control.indice :lc, :variaveis, :tipo1, :amplitude
    @lci_amplitude = @control.indice :lci, :variaveis, :tipo1, :amplitude
    @lcs_amplitude = @control.indice :lcs, :variaveis, :tipo1, :amplitude
    
    render "controls/variaveis/tipo3/amplitude"
  end
  
  def atributos_p
    @control = Control.find(params[:id])

    @lc = @control.indice :lc, :atributos, :p
    @lci = @control.indice :lci, :atributos, :p
    @lcs = @control.indice :lcs, :atributos, :p
    
    render "controls/atributos/p"
  end
  
  def atributos_np
    @control = Control.find(params[:id])

    @lc = @control.indice :lc, :atributos, :np
    @lci = @control.indice :lci, :atributos, :np
    @lcs = @control.indice :lcs, :atributos, :np
    
    render "controls/atributos/np"
  end
  
  def atributos_c
    @control = Control.find(params[:id])

    @lc = @control.indice :lc, :atributos, :c
    @lci = @control.indice :lci, :atributos, :c
    @lcs = @control.indice :lcs, :atributos, :c
    
    render "controls/atributos/c"
  end
  
end

app/helpers/controls_helper.rb
module ControlsHelper
end

app/views/controls/_form.html.erb
<div class="field">
	<%= f.label :nome %><br />
	<%= f.text_field :nome %>
</div>
<div class="field">
	<%= f.label :descricao %><br />
	<%= f.text_area :descricao %>
</div>
<div class="select-group">
<%= f.input :publico, :label=>"Público" %>
</div>

app/views/controls/_informacoes.html.erb
<h2><%= @control.nome %></h2>
<%= @control.descricao %>

app/views/controls/_sidebar.html.erb
<%= render "samples/sidebar" %>

app/views/controls/_tabela.html.erb
<table class="full">
	<thead>
		<tr class="alt">
			<th>Id</th>
			<th>Controle</th>
			<th>Data</th>
			<th></th>
		</tr>
	</thead>
	
	<tbody>
		<% @controls.each do |controle| %>
		<tr class="alt">
			<td><%= link_to controle.id, controle %></td>
			<td><%= link_to controle.nome, controle %></td>
			<td><%= l controle.created_at, :format=>:short %></td>
			<td>
			<!-- Icons -->
			<%= link_to image_tag('icons/edit.png'), edit_control_path(controle)%>
			<%= link_to image_tag('icons/delete.png'), controle, :method=>:delete %>
			</td>
		</tr>
		<% end %>
		</tbody>
</table>

app/views/controls/edit.html.erb
<%= simple_form_for(@control) do |f| %>
<% if @control.errors.any? %>
<div class="notification errors">
	<%= pluralize(@control.errors.count, "erro impediu", "erros impediram") %> o registro de ser salvo:
	<p class="collapsible collapsible-heading"><a href="#" class="collapsible-heading-toggle"><span class="collapsible-heading-status">Ocultar </span>Mostrar detalhes!</a></p>
	<ul class="collapsible-content" aria-hidden="false">
		<% @control.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>



<div class="innerdiv"> 
	<!-- Tabs --> 
	<h2 class="head-alt-white">Controles</h2> 
	<div class="innercontent"> 
		<!-- tab "panes" --> 
		<div class="panes"> 
			<div> 
				<fieldset> 
					<legend>Editar</legend> 
					<%= render "form", {:f=>f} %>
					<%= f.input :ls_padrao, :label=>"Limite Superior de Controle Padrão", :as=>:string %>
					<%= f.input :li_padrao, :label=>"Limite Inferior de Controle Padrão", :as=>:string %>
					<input class="button black bigger" type="submit" value="Salvar">
				</fieldset> 
			</div> 
		</div> 
	</div> 
</div> 
<% end %>

app/views/controls/index.html.erb
<div class="innerdiv"> 
	<h2 class="head-alt-white">Controle</h2> 
	<div class="innercontent">
		<%= render "tabela" %>
	</div>
</div>

app/views/controls/new.html.erb
<%= simple_form_for(@control) do |f| %>
<% if @control.errors.any? %>
<div class="notification errors">
	<%= pluralize(@control.errors.count, "erro impediu", "erros impediram") %> o registro de ser salvo:
	<p class="collapsible collapsible-heading"><a href="#" class="collapsible-heading-toggle"><span class="collapsible-heading-status">Ocultar </span>Mostrar detalhes!</a></p>
	<ul class="collapsible-content" aria-hidden="false">
		<% @control.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>



<div class="innerdiv"> 
	<!-- Tabs --> 
	<h2 class="head-alt-white">Controles</h2> 
	<div class="innercontent"> 
		<!-- tab "panes" --> 
		<div class="panes"> 
			<div> 
				<fieldset> 
					<legend>Novo Controle</legend> 
					<%= render "form", {:f=>f} %>
					<input class="button black bigger" type="submit" value="Salvar">
				</fieldset> 
			</div> 
		</div> 
	</div> 
</div> 
<% end %>

app/views/controls/show.html.erb
<div class="innerdiv"> 
	<h2 class="head-alt-white">Controle</h2> 
	<%= link_to "Configurar & Editar", edit_control_path(@control), :class=>"button top-button red" %>
	<ul class="tabs">
		<li><%= link_to "Informações", @control, :class=>"current"%></li>
		<li><%= link_to "Arquivos", control_sheets_path(@control)%></li>
		<li><%= link_to "Amostras", control_samples_path(@control)%></li>
	</ul>
	<div class="innercontent">
		<div class="panes">
				<%= render "informacoes" %>
		</div>
	</div>
</div>