config/routes.rb
Qualidade::Application.routes.draw do
  
  resources :items

  resources :controls do
    member do 
      get 'variaveis_tipo_1_media'
      get 'variaveis_tipo_1_amplitude'
      get 'variaveis_tipo_2_media'
      get 'variaveis_tipo_2_desvio_padrao'
      get 'variaveis_tipo_3_mediana'
      get 'variaveis_tipo_3_amplitude'
      get 'atributos_p'
      get 'atributos_np'
      get 'atributos_c'
    end
    resources :sheets do
      match :processar, :on => :member
    end
    resources :samples
  end

  devise_for :users
  resources :users

  get "home/index"

  root :to => "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"> 
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"> 
 
<head> 
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /> 
<title>CEP :: Controle Estatístico de Processos</title> 

<%= stylesheet_link_tag "main" %>
<%= stylesheet_link_tag "colors/red" %>
<%= stylesheet_link_tag "superfish" %>

 
<%= javascript_include_tag "jquery-1.4.2.min" %>
<%= javascript_include_tag "jquery.hoverIntent.minified" %>
<%= javascript_include_tag "superfish" %>
<%= javascript_include_tag "jquery.tools.min" %>
<%= javascript_include_tag "jquery.simplemodal" %>
<%= javascript_include_tag "jquery.notifyBar" %>
<%= javascript_include_tag "jquery.tipsy" %>
<%= javascript_include_tag "enhance" %>
<%= javascript_include_tag "excanvas" %>
<%= javascript_include_tag "visualize.jQuery" %>
<%= javascript_include_tag "jQuery.collapsible" %>
<%= javascript_include_tag "jquery.autoSuggest.packed" %>
<%= javascript_include_tag "platinum-admin" %>
<%= javascript_include_tag "highcharts" %>

<%= csrf_meta_tag %>
<%= javascript_include_tag "rails" %>

</head> 
 
<body> 
 
<div id="header"> 
	<div id="header-top"> 
		<div id="logo"> 
			<h1>CEP</h1> 
			<span id="slogan">controle estatístico de processos</span> </div> 
		<!-- end logo --> 
		<div id="login-info"> 
			<%= image_tag "icons/user.png", :id=>:profile %>
			<p id="top"><span id="name"><%= current_user.name %></span><br /> 
			<span id="links"> 
			<a id="message-link" href="#" title="click to see the messages!"> 
			
			<%= link_to 'sair', destroy_user_session_path, :id=>"power"%>
			
		</div> 
		<!-- end login --> 
		<div id="nav"> 
			<ul class="sf-menu sf-navbar"> 
				<li><%= link_to "Principal", root_path, :id=>"dashboard" %></li> 
				<li class="current"><a id="articles" href="#a">CEP's</a> 
				<ul> 
					<li class="current"><%= link_to "Novo Controle", new_control_path %></li> 
					<li><%= link_to "Gerenciar Controles", controls_path %></li> 
				</ul> 
				</li> 
				<li><a id="users" href="#">Usuários</a> 
				
				</li> 
				<li><a id="settings" href="#">Configurações</a> 
				
				</li> 
			</ul> 
		</div> 
		<!-- end div#nav --></div> 
	<!-- end div#header-top --> 
	<div class="breadCrumb">

		<%= render_navigation(:renderer => :breadcrumbs) %> 
	</div> 
	 
	<!-- end div#search-box --></div> 
<!-- end header --> 
<div id="page-wrap"> 
	<%= render "sidebar" rescue render "home/sidebar" %>
	<!-- end right-sidebar --> 
	<div id="main-content"> 
		<% if notice %>
		<div class="notification successfull closable">
			<%= notice %> <span class="closelink" title="Close"></span>
		</div>
		<% end %>
		
		<%= yield %>
		
	</div> 
	<!-- end main-content --></div> 
<!-- end page-wrap --> 
<div id="footer"> 
	<p>© 2010 sanderson.santana@gmail.com</p> 
</div> 
<!-- end footer --> 
 
</body> 
<script>
$(document).ready(function() {
	$(".breadCrumb li:first").addClass("first");
	$(".breadCrumb li:last").addClass("last");
	$("#main-content").css('min-height', 500)
});
</script>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
<title>CEP :: Controle Estatístico de Processos</title>

<%= stylesheet_link_tag "main" %>
<%= stylesheet_link_tag "colors/red" %>

 
<%= javascript_include_tag "jquery-1.4.2.min" %>
<%= javascript_include_tag "jquery.tools.min" %>
<%= javascript_include_tag "platinum-admin-login" %>


</head>

<body>

<div id="login">
	<h2 class="head-alt">CEP :: Login</h2>
	<ul class="tabs">
		<li><a href="#">Login</a></li>
		<li><a href="#">Cadastrar</a></li>
	</ul>
	<div class="panes">
		<div>
			<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
				<fieldset>
				<legend>Digite suas informações!</legend>
				<label for="username">Email:</label><%= f.text_field :email %>
				<label for="password">Senha:</label><%= f.password_field :password %>
				<input class="button" type="submit" value="Entrar!" />
				</fieldset>
			<% end %>
		</div>
		<div>
			<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
				<fieldset>
				<legend>Digite suas informações para se cadastrar!</legend>
				<label for="nome">Nome:</label><%= f.text_field :name %>
				<label for="username">Email:</label><%= f.text_field :email %>
				<label for="password">Senha:</label><%= f.password_field :password %>
				<label for="password_confirmation">Confirmação:</label><%= f.password_field :password_confirmation %>
				<input class="button red" type="submit" value="Registrar" />
				</fieldset>
			<% end %>
		</div>
	</div>
</div>

</body>

</html>